-- CreateEnum
CREATE TYPE "StoreNiche" AS ENUM ('FASHION_APPAREL', 'BEAUTY_SKINCARE', 'ELECTRONICS_GADGETS', 'FOOD_GROCERIES', 'HOME_LIVING', 'KIDS_BABY', 'HEALTH_WELLNESS', 'BOOKS_STATIONERY', 'ARTS_CRAFTS', 'OTHER');

-- AlterTable
ALTER TABLE "Store" ADD COLUMN     "niche" "StoreNiche" NOT NULL DEFAULT 'OTHER';
